### ISSUE TITLE
 Service flohmarkt is unknown

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/flohmarkt_ynh#18]
Hi, 
got some errors the diagnostics from Flohmarkt 0.0~ynh5
Yunohost 11.2.11.3 (stable)
` Service flohmarkt is unknown`
https://paste.yunohost.org/exazawotix

attempting to start the service resulted in an error
`Failed to get status information via dbus for service flohmarkt, systemctl didn't recognize this service ('NoSuchUnit').`

However, Flohmarkt still seems to work. 

Cheers

**Comment by chri2** [comment]
Hey and thanks for your feedback. From the log and what you describe I could not reproduce the error. 

Could you provide step-by-step information about what you did before you found this bug (e.g. installed, de-installed, installed again, restarted yunohost, could access the webpage, restarted flohmarkt service)?

Some more general information about the error:
* since ynh5 the service should be named flohmarkt_doma.in - maybe renaming didn't work through an update
  * `systemctl list unit-files | grep flohmarkt` on the command line should show the available units
  * `ls -l /etc/systemd/system/flohmarkt*` shows the service files available
  * `yunohost service status | grep -A5 ^flohmarkt` shows the systemd services registered in yunohost (that can be found in the web admin interface or through the `yunohost` command)
* problem accessing couchdb
  * flohmarkt doesn't seem to be able to connect to couchdb - ynh5 is the first version containing a different flohmarkt.conf syntax `cat /var/www/flohmarkt/app/flohmarkt.conf | grep -v '^Password\|^JwtSecret'` for the connection to couchdb
  * is couchdb running `systemctl status couchdb` 
  * couchdb has its port open? `netstat -pnlt | grep 5984` (should find the process beam.smp)
  * de-installing and installing anew could lead to the couchdb flohmarkt user still having the password of the first install while the second install created a new, but unknown password (https://codeberg.org/flohmarkt/flohmarkt_ynh/issues/54#issuecomment-1832948)
  
If you have access to your yunohost command line (ssh, console), could you paste the output of the mentioned commands? Please be careful to make sure they do not contain any data that you consider private.

**Comment by hermann-san** [comment]
@chri2   I did not do something. I just received an e-mail with automatic diagnostics.
Unless you consider visiting the site also something done :-).
Maybe I visited the site on that day or the day before. I can't remember when it was. Apart of that, nothing done from my side, at least regarding that app. 
On that day, the system did an auto-renewal of a lets Encrypt cert. Flohmarkt is mentioned many times in the debugs, but so are other installed apps mentioned. 
I can't see any error there. 

One day before, I did the upgrade to 0.0~ynh5
I also created a backup that day and updated another app.  YH was probably automatically restarted after the system upgrades (PHP 8.2 and 8.3). It was all successful without errors.

I will check later for the output of those commands.

**Comment by chri2** [comment]
Hm, seems like the update broke it... But let's see what you can find out using those commands.

**Comment by chri2** [comment]
@hermann-san do you have any new information on this issue?

**Comment by hermann-san** [comment]
yes, here is the output of those commands
https://pastebin.grey.pw/?da7b34c4ef9ef78d#AvcWeN5MnfBujrP49KbrRoENX6pBLNzR2gfVYoWgyf1o

**Comment by chri2** [comment]
* couchdb seems to be running and listening :heavy_check_mark: 
* I had an error in the first command - correct is `systemctl list-unit-files | grep flohmarkt`. (But I guess I know that there'll be no service file flohmarkt.service anymore).
* Somehow [this code](https://github.com/YunoHost-Apps/flohmarkt_ynh/blob/fd18937f4c3425a0d6b73a465eff8a0501a4a289/scripts/_common.sh#L213) failed its purpose to remove the old _flohmarkt.service_ from systemd.
* `flohmarkt.conf`: Database section seems to be configured o.k. for **IPv4**. By any chance: is there a problem to reach 127.0.0.1? You could try by `curl -X GET http://127.0.0.1:5984/` which should return json like `{"couchdb":"Welcome","version":"3.3.3"…`
* The **credentials** used could be wrong for any reason.
* Can't think of another reason why this fails.

## credentials

Some checks to get an overview:

### same in settings.yml and flohmarkt.conf

Compare the password from both files:

```bash
root@localhost:~# grep password_couchdb_flohmarkt /etc/yunohost/apps/flohmarkt/settings.yml ; grep -A6 '^.Database' /var/www/flohmarkt/app/flohmarkt.conf | grep '^User\|^Password'
password_couchdb_flohmarkt: my_secret_password
User = flohmarkt
Password = my_secret_password
```
The filenames shouldn't differ if this is your first or only installation of flohmarkt on that host.

### check database user

```bash
root@localhost:~# curl -s "http://127.0.0.1:5984/flohmarkt/_security" --user "admin:$(grep '^password_couchdb_admin: ' /etc/yunohost/apps/flohmarkt/settings.yml | cut -d' ' -f2)" -H "Accept: application/json" -H "Content-Type: application/json"
{"writers":{"names":["flohmarkt"],"roles":["editor"]}}
```

This curl command should login to couchdb as admin and return a json with all users registered. This needs to contain the `User = flohmar…` you found above in flohmarkt.conf

### check flohmarkt couchdb account password

`curl -s "http://127.0.0.1:5984/flohmarkt/" -H "Accept: application/json" -H "Content-Type: application/json" --user "$( grep -A6 '^.Database' /var/www/flohmarkt/app/flohmarkt.conf | grep '^User\|^Password' | cut -d' ' -f3 | paste -d: - - )"` should return a json like `{"instance_start_time":"1715933430","db_name":"flohmarkt",…`

## old systemd service

You should be able to remove the leftover systemd service `flohmarkt` by:

```bash
systemctl reset-failed
systemctl stop flohmarkt
systemctl disable flohmarkt
rm /etc/systemd/system/flohmarkt
systemctl daemon-reload
systemctl reset-failed
```

## what now

I don't know how much time you already put into configuring flohmarkt and putting items online. If it is an option for you to start over you'd need to de-install flohmarkt, make sure that couchdb got de-installed (no other app depending on it) and stopped, delete `/var/lib/couchdb/` to make sure no old users or data is left over and install again.

The problem of flohmarkts couchdb-data not getting completely removed on remove and might cause problems when upgrades failed is tracked [here](https://codeberg.org/flohmarkt/flohmarkt_ynh/issues/54). I hope I can solve that for ynh6.

**Comment by hermann-san** [comment]
```
systemctl list-unit-files | grep flohmarkt
[sudo] password for admin: 
flohmarkt_flohmarkt.mftools.de.service enabled         enabled
```
**_" is there a problem to reach 127.0.0.1?"_**
no problem. The command returns the text you mentioned.

**Credentials Check:** I've got 2 passwords with those grep commands and both are exactly the same. 

The username was "flohmarkt" and the database user check also gave me back "flohmarkt"
`{"writers":{"names":["flohmarkt"],"roles":["editor"]}}`

**"check flohmarkt couchdb account password
should return a json like ..."_**
yes, it does.

**old systemd service**
**But I guess I know that there'll be no service file flohmarkt.service anymore).**
it looks like the service is still there.
I guess I still should re-install, right?
I've not done much with the instance. Re-install is no Prob.

**Comment by hermann-san** [comment]
**"But I guess I know that there'll be no service file flohmarkt.service anymore)."**

```
systemctl list-unit-files | grep flohmarkt
[sudo] password for admin: 
flohmarkt_flohmarkt.****.de.service enabled         enabled
```
the service seems to be there

**" is there a problem to reach 127.0.0.1?"**
no problem. The command returns the text you mentioned.

**Credentials Check:** I've got 2 passwords with those grep commands and both are exactly the same.

**Database user**
```
{"writers":{"names":["flohmarkt"],"roles":["editor"]}}
```
The username was "flohmarkt" and the database user check also gave me back "flohmarkt"

**"check flohmarkt couchdb account password
should return a json like ..."_**
yes, it does.

**old systemd service
But I guess I know that there'll be no service file flohmarkt.service anymore).**
it looks like the service is still there.
I guess I still should re-install, right?
I've not done much with the instance. Re-install is no Prob.

**Comment by chri2** [comment]
I don't know. The only things I could think off we could try to find the cause would be:
* I send you a list to tar (or you just do a backup if that works) and you send me the files
  * your flohmarkt passwords and your couchdb admin password would be burned
  * I could look into the issue by installing your files on my host

And yes, it's good you didn't put much work into configuring, yet. A remove and install would be a good thing to test. If the error persists above could be of great help to improve what I did.

If you install anew, please delete the couchdb if you do not use it otherwise.

* remove flohmarkt as you would remove any other app
* check if couchdb is still present as a debian package: `dpkg-query -W | grep '^couchdb'`
  * if so this could already be the cause of the problem: flohmarkt app should be the only app having a dependency on couchdb and therefore it should be de-installed automatically when removing flohmarkt
* remove the couchdb database directory: `rm -rf /var/lib/couchdb`

Then you're ready to start over.

**Comment by chri2** [comment]
Could you solve the problem be re-installing?

**Comment by hermann-san** [comment]
I was able to re-install  and almost all looks good. I can setup flohmarkt, I can log-in, create items.
The only thing is that there is still an  old services entry in the YH Services with  this error message
`Error: failed to get information for this service, it doesn't exists for systemd`

I checked the app.log  and all looks good. No error/warning message. 

So it would be nice to be able to get rid of that old service entry. So I do have 2 entries there were there should only be one. it looks like the uninstall script has not removed that service.

![image](https://github.com/YunoHost-Apps/flohmarkt_ynh/assets/7679654/bc0d7cbe-fc8b-4ee2-8f01-f65fcf25f768)

**Comment by chri2** [comment]
That could be removed by:

```
yunohost service remove flohmarkt
yunohost service status | grep flohmarkt
```

The second command should afterwards show you only the one flohmarkt service with the domain in its name.

**Comment by hermann-san** [comment]
The service is gone. Thanks a lot for your help .

**Comment by hermann-san** [comment]
The service is gone. Thanks a lot for your help .
