### ISSUE TITLE
Not starting itself

### ISSUE THREAD

**Issue by Krzychencjusz** [YunoHost-Apps/flohmarkt_ynh#26]
Hello, flohmarkt is not starting after system reboot, and have to be manually started from "Services" tab. Any idea how to solve this problem?

**Comment by chri2** [comment]
I must admit I never tested the starting of flohmarkt after a reboot very well and there might be a prolem.

The service should start automatically by the generated systemd service file. Since flohmarkt relies on couchdb and a network interface to bind to network and couchdb need to be started beforehand. There should be dependencies for the service on those other services.

If you do have some knowledge about using the command line and systemd you could look at these pre-conditions whether I made a mistake here.

Otherwise I'll look into the issue next week and get back to you!

Thanks for reporting!

23.07.2024 18:30:33 Krzychencjusz ***@***.***>:

Hello, flohmarkt is not starting after system reboot, and have to be manually started from "Services" tab. Any idea how to solve this problem?

**Comment by chri2** [comment]
Do you still have this issue? Could you look into the configuration of systemd on your system? Do you need more help?

**Comment by Krzychencjusz** [comment]
After last update it seems to work as it should. I have no idea why I experienced that.

**Comment by chri2** [comment]
Thanks for the feedback!
